
name: Autoscaling CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted, custom-runner]
    steps:
      - name: Sleep for 60s
        uses: juliangruber/sleep-action@v1
        with:
          time: 60s
